---
title: "Read GPS data directly from server"
output: 
  pdf_document: 
    fig_height: 6
---

Read Ruth's GPS data via the API

```{r}
rm(list=ls()) 
library("jsonlite")
library(anytime)
library(lubridate)

Havørn <-    jsonlite::fromJSON('https://client.trusted.dk/Public/GetTrail?key=hmM3Tkj7Hqzd9bx1&id=88463&skip=0&count=10000')
Havterne <-  jsonlite::fromJSON('https://client.trusted.dk/Public/GetTrail?key=hHMt6mnY6lP559N5&id=88465&skip=0&count=10000')
Ismåge <-    jsonlite::fromJSON('https://client.trusted.dk/Public/GetTrail?key=AHvGej6oO38Tf2Uf&id=88464&skip=0&count=10000')
Mallemuk <-  jsonlite::fromJSON('https://client.trusted.dk/Public/GetTrail?key=oGpy6z41mAOjI35p&id=88462&skip=0&count=10000')
Søkonge <-   jsonlite::fromJSON('https://client.trusted.dk/Public/GetTrail?key=Qv6y9qee7SyOMTYZ&id=88319&skip=0&count=10000')
Edder <-     jsonlite::fromJSON('https://client.trusted.dk/Public/GetTrail?key=3U2RFGwXk74cDtTe&id=88617&skip=0&count=10000')
Fjeldrype <- jsonlite::fromJSON('https://client.trusted.dk/Public/GetTrail?key=yXbqk453gBAMV0sJ&id=81619&skip=0&count=6500')
```

# f
```{r}
returnlonlatUTC <- function(frame)
{
  df  <- NULL
  df$lon <- as.numeric(frame$Longitude)
  df$lat <- as.numeric(frame$Latitude)
  df$UTC <- anytime(frame$UnixTimestampUtc/1000,asUTC=T)
  df$Year <- year(df$UTC)
  df$Month <- month(df$UTC)
  df$Day <- day(df$UTC)
  df$Hour <- hour(df$UTC)
  df$Minute <- minute(df$UTC)
  df$UnitID <- frame$UnitId
  df <- as.data.frame(df)
  return(df)
}
```

# Merge into one frame 
```{r}


# WHy not rbind here????


df <- returnlonlatUTC(Havørn)
df2 <- df
df <- merge(df,returnlonlatUTC(Havterne),by=c("Year","Month","Day","Hour","Minute"),all=T)
df2 <- rbind.data.frame(df2,returnlonlatUTC(Havterne))
df <- merge(df,returnlonlatUTC(Ismåge),by=c("Year","Month","Day","Hour","Minute"),all=T)
df2 <- rbind.data.frame(df2,returnlonlatUTC(Ismåge))
df <- merge(df,returnlonlatUTC(Mallemuk),by=c("Year","Month","Day","Hour","Minute"),all=T)
df2 <- rbind.data.frame(df2,returnlonlatUTC(Mallemuk))
df <- merge(df,returnlonlatUTC(Søkonge),by=c("Year","Month","Day","Hour","Minute"),all=T)
df2 <- rbind.data.frame(df2,returnlonlatUTC(Søkonge))
df <- merge(df,returnlonlatUTC(Edder),by=c("Year","Month","Day","Hour","Minute"),all=T)
df2 <- rbind.data.frame(df2,returnlonlatUTC(Edder))
df <- merge(df,returnlonlatUTC(Fjeldrype),by=c("Year","Month","Day","Hour","Minute"),all=T)
df2 <- rbind.data.frame(df2,returnlonlatUTC(Fjeldrype))
nams <- colnames(df) 
idx <- grep('UTC',nams)
df <- df[,-idx] # drop the UTC columns
saveRDS(df2,"OUTPUT/updated_file_of_GPS_observations.rds")
```

# Inventory
```{r}
df3 <- readRDS("OUTPUT/updated_file_of_GPS_observations.rds")
IDs <- sort(unique(df3$UnitID))
for (id in IDs)
{ 
  idx <- which(df3$UnitID == id)
  if (id == 88319){
    kdx <- which(df3$lat[idx] > 77.64)
    idx <- idx[kdx]
  }
  
  print(paste(id,length(idx),anytime(range(df3$UTC[idx]),asUTC=T)))
  plot(df3$UTC[idx],df3$lat[idx],main=id) 
}
```



