---
title: "Ruth's GPS"
output: 
  pdf_document: 
    fig_height: 9
    fig_caption: yes
---
HALTED for now while the extra data are located.


Version 4 triad: like 4, but focuses on the three sensors left close together: GPS Mallemuk, Ismåge and Havtern (+ Strandskade)  that were deployed in a triangle from 28/03 ~~ 19.30 to 30/03 15.00 (UTC)

```{r, message=FALSE,warning=FALSE}
rm(list=ls())
library(MASS)
library(ie2misc)
library(dplyr)
library(lubridate)
setwd("~/WORKSHOP/GPS/")

df <- readRDS("OUTPUT/EVERYTHING4.rds")
# clean out columns with only NA
listen <- NULL
for (icol in 1:ncol(df))
{    listen <- rbind(listen,c(icol,colSums(is.na(df[,icol]))))}
idx <- which(listen[,2] == nrow(df))
df <- df[,-idx]
df$POSIX <- as.POSIXct(df$"Timestamp UTC",tz="UTC")
idx <- which(df$POSIX >= as.POSIXct("2022-03-29 23-00-00") & df$POSIX < as.POSIXct("2022-03-30 15-00-00"))
df <- df[idx,]
df_org <- df
#
unique_names <- unique(df$UnitName)
unique_names

```

# Select just the four mentioned
```{r}

# select just the four stations mentioned
fourstations <- c("Mallemuk 300434066431710","Ismaage 300434066437720","Havterne 300434066435700") #,"Strandskade 860640050251356")
dfnew <- NULL
for (iset in fourstations)
{
  idx <- which(df$UnitName == iset) 
  print(c(iset,length(idx)))
  dfnew <- rbind.data.frame(dfnew,df[idx,])
}
```






# read
```{r}
statdat <- NULL
alldf <- NULL

par(mfrow=c(3,3))
for (istat in c("Mallemuk 300434066431710", "Ismaage 300434066437720","Havterne 300434066435700")) # ,"Strandskade 860640050251356"))
{
  
  idx <- which(df_org$UnitName == istat  )
  df2 <- df_org[idx,]  
  
  lon <- df2$Longitude
  lat <- df2$Latitude
  time <- df2$POSIX
  
  plot(lon,lat,main=istat,pch=19,cex=0.2,type="p")
  plot(time,lon,main=istat,pch=19,cex=0.2,type="b")
  plot(time,lat,main=istat,pch=19,cex=0.2,type="b")
  
  #
  
}

```




