---
title: "Plot positions and speeds"
output: 
  pdf_document: 
    fig_height: 9
---


Version 3: calculates speed at the sudden changes in location.

Reads .xlsx files
Outputs .rds files for columns not all NA

```{r}
rm(list=ls())
setwd("~/WORKSHOP/GPS/")
library(dplyr)
library(lubridate)


```

## Utility GC formula
```{r}

# Calculates the geodesic distance between two points specified by radian latitude/longitude using the
# Haversine formula (hf)
gcd.hf <- function(long1, lat1, long2, lat2) {
  R <- 6371*1000 # Earth mean radius [m]
  delta.long <- (long2 - long1)
  delta.lat <- (lat2 - lat1)
  a <- sin(delta.lat/2)^2 + cos(lat1) * cos(lat2) * sin(delta.long/2)^2
  c <- 2 * asin(min(1,sqrt(a)))
  d = R * c
  return(d) # Distance in m
}

```

# Define function to calculate speed
```{r}
getSpeed <- function(time,lon,lat)
{
  rtod <- pi/180
  speed <- NULL
  speed_smoo <- NULL
  for (it in 1:(length(time)-1))
  {
    # calc great-circle distance between pairs of points
    distance <- gcd.hf(rtod*lon[it+1],rtod*lat[it+1],rtod*lon[it],rtod*lat[it])
    delta_time <- as.numeric(time[it+1]-time[it])/60 # dt in hours now
    #browser()
    # calc speed
    speed <- c(speed,abs(distance/delta_time))
  }
  speed_smoo <- NULL
  for (j in 1:(length(speed)-1))
  {
    speed_smoo <- rbind(speed_smoo,c(j,median(c(speed[j-2],speed[j-1],speed[j],speed[j+1],speed[j+1]),na.rm=TRUE)))
  }
  speed_smoo <- rbind(speed_smoo[1,],speed_smoo,speed_smoo[nrow(speed_smoo),])
  #browser()
  return(list("speed"=speed,"speed_smoo"=speed_smoo))
}
```

# Plot coloured points
```{r}
plotcolouredpoints <- function(x,y,limitdates,pair,ivar)
{
  idx <- which(df$POSIX >= limitdates[(pair-1)*2+1] & df$POSIX < limitdates[(pair-1)*2+2])
  points(x[idx],y[idx],type="p",cex=0.3,col=1+pair)
  if (ivar == 'speed') {print(paste(pair,' from ',limitdates[(pair-1)*2+1],' to ', limitdates[(pair-1)*2+2],' speed: ',round(median(y[idx],na.rm=T),1),' +/- ',round(sd(y[idx],na.rm=T)/sqrt(length(idx)),1), 'm/hr'))}
 
}
```



# plot positions and speeds etc
```{r}
plot_stuff <- function(df,name,limitdates)
{
  par(mfrow=c(4,1))
  nlimits <- length(limitdates)
  statname <- strsplit(strsplit(name, "/")[[1]][2],".rds")[[1]][1]
  # First plot positions
  plot(df$Longitude,df$Latitude,type="p",cex=0.3,xlab="lon",ylab="lat",main=statname)
  plotcolouredpoints(df$Longitude,df$Latitude,limitdates,1,'')
  plotcolouredpoints(df$Longitude,df$Latitude,limitdates,2,'')
  plotcolouredpoints(df$Longitude,df$Latitude,limitdates,3,'')
  plotcolouredpoints(df$Longitude,df$Latitude,limitdates,4,'')
  # Plot lon vs time
  plot(df$POSIX,df$Longitude,type="p",cex=0.3,xlab="Date/Time",ylab="lon",main=statname)
  plotcolouredpoints(df$POSIX,df$Longitude,limitdates,1,'')
  plotcolouredpoints(df$POSIX,df$Longitude,limitdates,2,'')
  plotcolouredpoints(df$POSIX,df$Longitude,limitdates,3,'')
  plotcolouredpoints(df$POSIX,df$Longitude,limitdates,4,'')
  # Plot lat vs time
  plot(df$POSIX,df$Latitude,type="p",cex=0.3,xlab="Date/Time",ylab="lat",main=statname)
  plotcolouredpoints(df$POSIX,df$Latitude,limitdates,1,'')
  plotcolouredpoints(df$POSIX,df$Latitude,limitdates,2,'')
  plotcolouredpoints(df$POSIX,df$Latitude,limitdates,3,'')
  plotcolouredpoints(df$POSIX,df$Latitude,limitdates,4,'')
  # get speed
  out <- getSpeed(df$POSIX,df$Longitude,df$Latitude)
  speed <- out$speed
  speed_smoo <- out$speed_smoo[,2]
  df$speed <- c(speed[1],speed)
  df$speed_smoo <- speed_smoo
  #browser()
  # plot speed against time
  plot(df$POSIX,df$speed,type="p",cex=0.3,xlab="Date/Time",ylab="speed [m/hr]",main=statname)
  plotcolouredpoints(df$POSIX,df$speed,limitdates,1,'speed')
  plotcolouredpoints(df$POSIX,df$speed,limitdates,2,'speed')
  plotcolouredpoints(df$POSIX,df$speed,limitdates,3,'speed')
  plotcolouredpoints(df$POSIX,df$speed,limitdates,4,'speed')
  #lines(df$POSIX,df$speed_smoo)
  }
```

# model positions and calculate speeds at jumps
```{r}
get_jump_speeds_by_postion_modelling <- function(df,name,limitdates)
{
  par(mfrow=c(4,1))
  nlimits <- length(limitdates)
  statname <- strsplit(strsplit(name, "/")[[1]][2],".rds")[[1]][1]
  # loop over limidates and model positions before and after each limitdate
  
  }
```

# read and plot each file
```{r,fig.width=6,fig.height=9}
files <- c('OUTPUT/Mallemuk.rds','OUTPUT/Soekonge.rds','OUTPUT/Ismaage.rds','OUTPUT/Havterne.rds','OUTPUT/Havoern.rds','OUTPUT/Edder.rds')
#files <- files[1]
limitdates <- c(as.POSIXct("2022-03-31 00:00:00",tz="UTC"),as.POSIXct("2022-04-7 00:00:00",tz="UTC"),
                as.POSIXct("2022-04-7 00:00:00",tz="UTC"),as.POSIXct("2022-04-24 12:00:00",tz="UTC"),
                as.POSIXct("2022-04-24 12:00:00",tz="UTC"),as.POSIXct("2022-04-27 17:00:00",tz="UTC"),
                as.POSIXct("2022-04-27 17:00:00",tz="UTC"),as.POSIXct("2022-05-04 00:00:00",tz="UTC")) 

for (ifil in 1:length(files))
{
  print(paste(" Processing file ",files[ifil]))
  df <- readRDS(files[ifil])
  plot_stuff(df,files[ifil],limitdates)
  get_jump_speeds_by_postion_modelling(df,files[ifil],limitdates)
}

```


