---
title: "Plot positions and speeds"
output: 
  pdf_document: 
    fig_height: 9
---

DOES NOT WORK YET surge speeds are about 10x too large and Soekonge a.o. are not read in properly

Version 4: plots from GPS data previously fetched from server with code "xxx.Rmd"

```{r}
rm(list=ls())
setwd("~/WORKSHOP/GPS/")
library(dplyr)
library(anytime)
library(lubridate)
library(MASS)

Rearth <- 6371*1e3 # meters

delta_t <- 0.66 # hours - estimated duration of a 'surge' (i.e. 1 time step in the data)
```


```{r}
# read data stored previously by code "GPS_from_server_1.Rmd"
data <- readRDS("OUTPUT/updated_file_of_GPS_observations.rds")
data$UTC <- as.POSIXct(data$UTC,tz="UTC")
idx <- which(data$Month < 4)
data <- data[-idx,] # skip all data before March 31st
unitIDs <- unique(data$UnitID)
#idx <- order(unitIDs)
#unitIDs <- unitIDs[rev(idx)]
#========================================================================
# Have to patch Mallemuk from older file
Mallemuk <- readRDS("OUTPUT/Mallemuk.rds")
Mallemuk$`Timestamp UTC` <- as.POSIXct(Mallemuk$`Timestamp UTC`,tz="UTC")
nyM <- Mallemuk[,c("Longitude","Latitude","Timestamp UTC")]
nyM$Year <- year(nyM$`Timestamp UTC`)
nyM$Month <- month(nyM$`Timestamp UTC`)
nyM$Day <- day(nyM$`Timestamp UTC`)
nyM$Hour <- hour(nyM$`Timestamp UTC`)
nyM$Minute <- minute(nyM$`Timestamp UTC`)
nyM$UnitID <- 88462
nyM <- na.omit(nyM)
nams <- colnames(data)
colnames(nyM) <- nams
# join
data <- rbind.data.frame(data,nyM)
#========================================================================
# Have to patch Soekonge from older file
Soekonge <- readRDS("OUTPUT/Soekonge.rds")
Soekonge$`Timestamp UTC` <- as.POSIXct(Soekonge$`Timestamp UTC`,tz="UTC")
nyS <- Soekonge[,c("Longitude","Latitude","Timestamp UTC")]
nyS$Year <- year(nyS$`Timestamp UTC`)
nyS$Month <- month(nyS$`Timestamp UTC`)
nyS$Day <- day(nyS$`Timestamp UTC`)
nyS$Hour <- hour(nyS$`Timestamp UTC`)
nyS$Minute <- minute(nyS$`Timestamp UTC`)
nyS$UnitID <- 88319
nyS <- na.omit(nyS)
nams <- colnames(data)
colnames(nyS) <- nams
# join
data <- rbind.data.frame(data,nyS)
# remove duplicated rows across dataframe
hej <- data %>%  distinct(.keep_all = FALSE)
data <- hej
write.table(data,"OUTPUT/dummy.csv",sep=";",quote = F,row.names = F)
data <- read.csv2("OUTPUT/dummy.csv",sep=";",stringsAsFactors = FALSE)
data$lon <- as.numeric(data$lon)
data$lat <- as.numeric(data$lat)
data$UTC <- ISOdatetime(data$Year,data$Month,data$Day,data$Hour,data$Minute,sec=0,tz="UTC")
saveRDS(data,"OUTPUT/combined_GPS_data.rds")
```

## Utility GC formula
```{r}

# Calculates the geodesic distance between two points specified by radian lat/lon using the
# Haversine formula (hf)
gcd.hf <- function(long1, lat1, long2, lat2) {
  R <- 6371*1000 # Earth mean radius [m]
  delta.long <- (long2 - long1)
  delta.lat <- (lat2 - lat1)
  a <- sin(delta.lat/2)^2 + cos(lat1) * cos(lat2) * sin(delta.long/2)^2
  c <- 2 * asin(min(1,sqrt(a)))
  d = R * c
  return(d) # Distance in m
}

```

 

# Plot coloured points
```{r}
plotcolouredpoints <- function(x,y,limitdates,ipair,ivar)
{
  idx <- which(df$UTC >= limitdates[ipair,1] & df$UTC < limitdates[ipair,2])
  points(x[idx],y[idx],type="p",cex=0.3,col=1+ipair)
}
```



# plot positions and speeds etc
```{r}
plot_stuff <- function(df,name,limitdates)
{
  par(mfrow=c(3,1))
  npairs <- nrow(limitdates)
  statname <- name
  # First plot positions
  plot(df$lon,df$lat,type="p",cex=0.3,xlab="lon",ylab="lat",main=statname)
  for (ipair in 1:npairs){  plotcolouredpoints(df$lon,df$lat,limitdates,ipair,'')  }
  # Plot lon vs time
  plot(df$UTC,df$lon,type="p",cex=0.3,xlab="Date/Time",ylab="lon",main=statname)
  for (ipair in 1:npairs){  plotcolouredpoints(df$UTC,df$lon,limitdates,ipair,'')  }
  # Plot lat vs time
  plot(df$UTC,df$lat,type="p",cex=0.3,xlab="Date/Time",ylab="lat",main=statname)
  for (ipair in 1:npairs){  plotcolouredpoints(df$UTC,df$lat,limitdates,ipair,'')  }
}
```

# model positions and calculate speeds at jumps
```{r}
model_motion <- function(df,statname,limitdates)
{
  nsegments <- nrow(limitdates)
  lat_speed <- NULL
  lon_speed <- NULL
  # loop over limitdates and model motion during segments of smooth motion (i.e. not the surges)
  for (isegment in 1:(nsegments-1))
  {
 #browser()
    # lat
    # first segment
    idx <- which(df$UTC >= limitdates[isegment,1] & df$UTC < limitdates[isegment,2] )
    rlmfit1 <- rlm(df$lat[idx] ~ df$UTC[idx])
    lat_speed1 <- summary(rlmfit1)$coefficients[2]*3600/180*pi # radians per hour
 
    # second segment
    jdx <- which(df$UTC >= limitdates[isegment+1,1] & df$UTC < limitdates[isegment+1,2] )
    rlmfit2 <- rlm(df$lat[jdx] ~ df$UTC[jdx])
    lat_speed2 <- summary(rlmfit2)$coefficients[2]*3600/180*pi # radians per hour
    
    # speed during jump between segments
    lat_jump <- rlmfit2$fitted.values[1]-rlmfit1$fitted.values[length(rlmfit1$fitted.values)]
    lat_speed <- rbind(lat_speed,c(isegment,lat_speed1,lat_jump))
    
    # lon
    # first segment
    kdx <- which(df$UTC >= limitdates[isegment,1] & df$UTC < limitdates[isegment,2] )
    rlmfit1 <- rlm(df$lon[kdx] ~ df$UTC[kdx])
    lon_speed1 <- summary(rlmfit1)$coefficients[2]*3600/180*pi # radians per hour
    
    # second segment
    ldx <- which(df$UTC >= limitdates[isegment+1,1] & df$UTC < limitdates[isegment+1,2] )
    rlmfit2 <- rlm(df$lon[ldx] ~ df$UTC[ldx])
    lon_speed2 <- summary(rlmfit2)$coefficients[2]*3600/180*pi # radians per hour
    
    # speed during jump between segments
    lon_jump <- rlmfit2$fitted.values[1]-rlmfit1$fitted.values[length(rlmfit1$fitted.values)]
    lon_speed <- rbind(lon_speed,c(isegment,lon_speed1,lon_jump))
  }
  # add speed during last segment
  lat_jump <- NA
  lat_speed <- rbind(lat_speed,c(isegment,lat_speed2,lat_jump))
  lon_jump <- NA
  lon_speed <- rbind(lon_speed,c(isegment,lon_speed2,lon_jump))
  
  colnames(lat_speed) <- c("segment_number","lat1_speed_radperhr","lat_jump_radians")
  colnames(lon_speed) <- c("segment_number","lon1_speed_radperhr","lon_jump_radians")
  segment_speed <- Rearth*sqrt((lon_speed[,2]*cos(median(df$lat,na.rm=T)/180*pi))^2+(lat_speed[,2])^2) # meters per hour
  #browser()
  return(list("lats"=lat_speed,"longs"=lon_speed,"segspeed"=segment_speed))
}
```

# function to get interval and jump speeds
```{r}
get_surge_speeds <- function(listerne,lon_in,lat_in)
{
   
  lon <- lon_in/180*pi # in radians
  lat <- lat_in/180*pi
  delta_t <- 3 # hours
  
  # calculate jump speeds
  n_segments <- nrow(listerne$lats)
  speed <- NULL
  for (iseg in 1:(n_segments-1))
  {
    delta_lon <- listerne$longs[iseg,3]
    delta_lat  <- listerne$lats[iseg,3]
     
    speed <- rbind.data.frame(speed,c(iseg,Rearth/delta_t*sqrt(delta_lon^2*cos(lat)^2+delta_lat^2))) # in meters/hr
  }
  colnames(speed) <- c("jump_number","speed_metersph")
  return(list("speed_jump"=speed))
}
```

# read and plot each file
```{r,fig.width=6,fig.height=9}
# specify the important intervals:
important_times <- c(as.POSIXct("2022-03-31 00:00:00",tz="UTC"),as.POSIXct("2022-04-07 00:00:00",tz="UTC"),
                     as.POSIXct("2022-04-07 00:00:00",tz="UTC"),as.POSIXct("2022-04-24 12:00:00",tz="UTC"),
                     as.POSIXct("2022-04-24 12:00:00",tz="UTC"),as.POSIXct("2022-04-27 12:00:01",tz="UTC"),
                     as.POSIXct("2022-04-27 12:00:01",tz="UTC"),as.POSIXct("2022-05-03 03:00:00",tz="UTC"),
                     as.POSIXct("2022-05-03 03:00:00",tz="UTC"),as.POSIXct("2022-05-19 22:00:00",tz="UTC"),
                     as.POSIXct("2022-05-19 22:00:00",tz="UTC"),as.POSIXct("2022-06-09 02:00:00",tz="UTC")
)
limitdates <- NULL
for (it in seq(from=1,to=length(important_times),by=2))
{  limitdates <- rbind(limitdates,c(anytime(important_times[it],asUTC=T),anytime(important_times[it+1],asUTC=T)))}

for (i_unitID in unitIDs)
{
  print("------------------------------------------")
  print(paste(" Processing unitID ",i_unitID))
  mdx <- which(data$UnitID == i_unitID)
  df <- data[mdx,]
  plot_stuff(df,i_unitID,limitdates)
  
  # model speed as unconnected straight line segments
  listerne <- model_motion(df,i_unitID,limitdates)
  
  segspeeds <- round(listerne$segspeed,2)
  print("Segment speeds in m/hr : ")
  print(segspeeds)
  # get surge speeds
  speeds <- get_surge_speeds(listerne,lon=median(df$lon,na.rm=T),lat=median(df$lat,na.rm=T))
  print(speeds)
  
}
print("------------------------------------------")
```


